# Generated by Django 3.0 on 2022-10-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsubject', models.CharField(max_length=120)),
                ('ntitle', models.CharField(max_length=120)),
                ('ndesc', models.CharField(max_length=200)),
            ],
        ),
    ]
